version: '2'
services:
    hlschool-app:
        image: hlschool
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hlschool-mysql:3306/hlschool?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hlschool-mysql:
        extends:
            file: mysql.yml
            service: hlschool-mysql
